export const routerEnum = {
    "/":'首页',
    '/brand':'brand zone',
    '/campaign':'campaign zone',
    '/lifestyle':'lifestyle zone',
    '/me':'me',
    '/agreement':'用户协议',
    '/article':'文章详情',
    '/faq':'常见问题',
    '/myChest':'ID.百宝箱',
    '/myInfo':'个人信息',
    '/myLike':'我的喜欢',
    '/myPost':'我的发布',
    '/post':'帖子详情',
    '/postPush':'帖子发布',
    '/privacy':'隐私协议',
    '/search':'搜索页',
    '/searchResult':'搜索结果页',
    '/service':'在线客服',
    '/serviceDetail':'客服回复',
    '/servicePush':'发起咨询',
    '/setting':'设置',
    '/tag':'标签详情',
    '/topic':'主题列表',
    '/topicDetail':'主题详情',
    '/myIdValue':'ID.值',
    '/anthemFilm':'AnthemFilm',
    '/arConcert':'ARConcert',
    '/brand/meb':'MEB',
    '/brand/idFamily':'Concept Car',
    '/brand/introduce':'ID. Statement',
    '/myActivity':'我的发布',
    '/myIdValueHistory':'',
    '/news':'news',
    '/showPhoto':'showPhoto',
    '/warmUp':'warmUp',
    '/tagAr':'"AR现场"'

};